server:
  port: 8082
  servlet:
    context-path: /api

#Logger configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %cyan(%class{0}) : %highlight(%msg%n)"

spring:
  datasource:
    url: jdbc:h2:mem:carShop
    driverClassName: org.h2.Driver
    username: sa
    password: password
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true