server:
  port: 8082
  servlet:
    context-path: /api

#Logger configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %cyan(%class{0}) : %highlight(%msg%n)"

spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/carShop;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop
  h2:
    console:
      enabled: true

app:
  secret: the_secret
  token-validity-in-seconds: 2592000
  jwt:
    token-name: CAR-SHOP-TOKEN